### ISSUE TITLE
Do we need dummyindex?

### ISSUE THREAD

**Issue by parrot64** [parrot64/ENDLESS#11]
i thought if dummy index is usless and i really dont know what it does so if some would explain it that would be great!

**Comment by DanilKorotenko** [comment]
![image](https://github.com/parrot64/ENDLESS/assets/2341646/8a807514-b20b-4dfc-b4a1-7f37ff5a29b6)

DummyIndex is using here

**Comment by DanilKorotenko** [comment]
We take random number between 1 and max dummyIndex
And then load dummy from that random number

**Comment by DanilKorotenko** [comment]
To provide random dummy generation, I think we need dummy index.
Because we can make a list of dummyies and then take one of them by random number.

**Comment by parrot64** [comment]
thanks!
