### ISSUE TITLE
Let's discuss the site view.

### ISSUE THREAD

**Issue by DanilKorotenko** [parrot64/ENDLESS#8]
May be we should choose another theme?
![image](https://github.com/parrot64/ENDLESS/assets/2341646/498918fc-519e-4589-be08-fb60aa2a206b)

**Comment by DanilKorotenko** [comment]
![image](https://github.com/parrot64/ENDLESS/assets/2341646/edeed45e-7671-455f-a63f-c6b3fcd85911)

https://pages.github.com/themes/

**Comment by parrot64** [comment]
hmm yeah meabe we should!midnigh,merlot,minima and cayman are really cool!

**Comment by parrot64** [comment]
sorry i didnt mean to close the issue

**Comment by parrot64** [comment]
also we should add a logo
